{% set name = "flask-openapi3" %}
{% set version = "4.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/flask_openapi3-{{ version }}.tar.gz
  sha256: e7932284263083eeb1f35c6657f6a4d1bb98be76f18f0509bd230e67f9854467

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - Flask >=2.0
    - pydantic >=2.0

test:
  imports:
    - flask_openapi3
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/luolingchun/flask-openapi3
  summary: Generate REST API and OpenAPI documentation for your Flask project.
  description: Generate REST API and OpenAPI documentation for your Flask project.
  doc_url: https://luolingchun.github.io/flask-openapi3/
  license: MIT
  license_file:
    - LICENSE.rst

extra:
  recipe-maintainers:
    - luolingchun
