{% set name = "flask-openapi3" %}
{% set version = "2.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 430d0701e498189c651997bb1720504244d5b79385f828d7385e940c79d4c6ac

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - Flask >=2.0
    - pydantic >=1.2,<2.0.0

test:
  imports:
    - flask_openapi3
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/luolingchun/flask-openapi3
  summary: Generate REST API and OpenAPI documentation for your Flask project.
  description: Generate REST API and OpenAPI documentation for your Flask project.
  doc_url: https://luolingchun.github.io/flask-openapi3/
  license: MIT
  license_file:
    - LICENSE.rst

extra:
  recipe-maintainers:
    - luolingchun
