{% set name = "flask-openapi3" %}
{% set version = "3.0.0rc2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flask_openapi3-{{ version }}.tar.gz
  sha256: 1a0306cd7253dd18534f904c867303bb7cecf36bf6df78c44e25aa601e56af26

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling
  run:
    - python >=3.8
    - Flask >=2.0
    - pydantic >=2.0

test:
  imports:
    - flask_openapi3
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/luolingchun/flask-openapi3
  summary: Generate REST API and OpenAPI documentation for your Flask project.
  description: Generate REST API and OpenAPI documentation for your Flask project.
  doc_url: https://luolingchun.github.io/flask-openapi3/
  license: MIT
  license_file:
    - LICENSE.rst

extra:
  recipe-maintainers:
    - luolingchun
